In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df_train = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')
submit = pd.read_csv('sample_submission.csv')

In [3]:
df_train.head()

,INCIDENT_ID,DATE,X_1,X_2,X_3,X_4,X_5,X_6,X_7,X_8,X_9,X_10,X_11,X_12,X_13,X_14,X_15,MULTIPLE_OFFENSE
0,CR_102659,04-JUL-04,0,36,34,2,1,5,6,1,6,1,174,1.0,92,29,36,0
1,CR_189752,18-JUL-17,1,37,37,0,0,11,17,1,6,1,236,1.0,103,142,34,1
2,CR_184637,15-MAR-17,0,3,2,3,5,1,0,2,3,1,174,1.0,110,93,34,1
3,CR_139071,13-FEB-09,0,33,32,2,1,7,1,1,6,1,249,1.0,72,29,34,1
4,CR_109335,13-APR-05,0,33,32,2,1,8,3,0,5,1,174,0.0,112,29,43,1

In [4]:
df_test.head()

,INCIDENT_ID,DATE,X_1,X_2,X_3,X_4,X_5,X_6,X_7,X_8,X_9,X_10,X_11,X_12,X_13,X_14,X_15
0,CR_195453,01-FEB-18,0,30,35,7,3,6,4,0,5,1,174,NaN,72,119,23
1,CR_103520,05-MAR-04,0,44,44,1,3,7,1,4,6,1,316,0.0,12,29,34
2,CR_196089,27-JAN-18,0,34,33,3,5,2,7,3,0,1,316,1.0,72,0,34
3,CR_112195,18-AUG-06,7,3,2,3,5,9,8,0,5,1,174,1.0,112,87,34
4,CR_149832,31-OCT-11,0,7,8,7,3,2,7,1,5,1,174,0.0,112,93,43

Let us have a look on the distribution of dataset

In [308]:
df_train.describe()

,X_1,X_2,X_3,X_4,X_5,X_6,X_7,X_8,X_9,X_10,X_11,X_12,X_13,X_14,X_15,MULTIPLE_OFFENSE
count,23856.000000,23856.000000,23856.000000,23856.000000,23856.000000,23856.000000,23856.000000,23856.000000,23856.000000,23856.000000,23856.000000,23674.000000,23856.000000,23856.000000,23856.000000,23856.000000
mean,0.483778,24.791206,24.637450,4.276744,2.455609,6.154175,4.876509,0.972460,4.924128,1.244802,206.954519,0.974064,85.237383,72.674296,33.464747,0.955231
std,1.439738,15.240231,15.135093,2.944672,1.963095,4.471756,3.881931,1.453144,1.362625,1.119301,93.033348,1.167725,27.597226,43.297320,8.386834,0.206800
min,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,7.000000,8.000000,2.000000,1.000000,3.000000,2.000000,0.000000,5.000000,1.000000,174.000000,1.000000,72.000000,29.000000,34.000000,1.000000
50%,0.000000,24.000000,24.000000,4.000000,3.000000,5.000000,4.000000,1.000000,5.000000,1.000000,249.000000,1.000000,98.000000,62.000000,34.000000,1.000000
75%,0.000000,36.000000,35.000000,6.000000,5.000000,8.000000,7.000000,1.000000,6.000000,1.000000,249.000000,1.000000,103.000000,107.000000,34.000000,1.000000
max,7.000000,52.000000,52.000000,10.000000,5.000000,19.000000,18.000000,99.000000,6.000000,90.000000,332.000000,90.000000,116.000000,142.000000,50.000000,1.000000

In [309]:
df_test.describe()

,X_1,X_2,X_3,X_4,X_5,X_6,X_7,X_8,X_9,X_10,X_11,X_12,X_13,X_14,X_15
count,15903.000000,15903.000000,15903.000000,15903.000000,15903.000000,15903.000000,15903.000000,15903.000000,15903.000000,15903.000000,15903.000000,15776.000000,15903.000000,15903.000000,15903.000000
mean,0.468088,24.722631,24.575049,4.284223,2.448469,6.084890,4.862605,0.986732,4.908759,1.241212,206.954097,0.972236,85.191096,72.218575,33.422625
std,1.412112,15.228841,15.127451,2.974584,1.963372,4.451117,3.854550,1.471274,1.374677,0.841804,93.107783,0.876669,27.493192,43.438227,8.314284
min,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,7.000000,8.000000,2.000000,1.000000,3.000000,2.000000,0.000000,5.000000,1.000000,174.000000,1.000000,72.000000,29.000000,34.000000
50%,0.000000,24.000000,24.000000,4.000000,3.000000,5.000000,4.000000,1.000000,5.000000,1.000000,249.000000,1.000000,98.000000,62.000000,34.000000
75%,0.000000,36.000000,35.000000,6.000000,5.000000,8.000000,7.000000,1.000000,6.000000,1.000000,249.000000,1.000000,103.000000,107.000000,34.000000
max,7.000000,52.000000,52.000000,10.000000,5.000000,19.000000,18.000000,50.000000,6.000000,40.000000,332.000000,40.000000,117.000000,142.000000,50.000000

Now I analyzed the difference in the statistical values of both the dataset & I figured out that both the dataset is having same mean and standard deviation.

So I analyzed that my dataset is having **low variance**

In [310]:
df_train.describe().drop(['count']).subtract(df_test.describe().drop(['count'])).drop(['MULTIPLE_OFFENSE'], axis =1)

,X_1,X_10,X_11,X_12,X_13,X_14,X_15,X_2,X_3,X_4,X_5,X_6,X_7,X_8,X_9
mean,0.015690,0.003590,0.000422,0.001828,0.046287,0.455721,0.042122,0.068575,0.062401,-0.007479,0.007140,0.069285,0.013905,-0.014272,0.015369
std,0.027626,0.277496,-0.074435,0.291057,0.104034,-0.140906,0.072550,0.011390,0.007641,-0.029912,-0.000278,0.020639,0.027381,-0.018129,-0.012053
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,0.000000,50.000000,0.000000,50.000000,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,49.000000,0.000000

Finding the NULL values & treating them

In [311]:
df_train.isnull().sum()

INCIDENT_ID           0
DATE                  0
X_1                   0
X_2                   0
X_3                   0
X_4                   0
X_5                   0
X_6                   0
X_7                   0
X_8                   0
X_9                   0
X_10                  0
X_11                  0
X_12                182
X_13                  0
X_14                  0
X_15                  0
MULTIPLE_OFFENSE      0
dtype: int64

In [312]:
df_test.isnull().sum()

INCIDENT_ID      0
DATE             0
X_1              0
X_2              0
X_3              0
X_4              0
X_5              0
X_6              0
X_7              0
X_8              0
X_9              0
X_10             0
X_11             0
X_12           127
X_13             0
X_14             0
X_15             0
dtype: int64

In [5]:
df_train['X_12'] = df_train['X_12'].replace(np.NaN, df_train['X_12'].mean())

df_train.isnull().sum()

INCIDENT_ID         0
DATE                0
X_1                 0
X_2                 0
X_3                 0
X_4                 0
X_5                 0
X_6                 0
X_7                 0
X_8                 0
X_9                 0
X_10                0
X_11                0
X_12                0
X_13                0
X_14                0
X_15                0
MULTIPLE_OFFENSE    0
dtype: int64

In [6]:
df_test['X_12'] = df_test['X_12'].replace(np.NaN, df_test['X_12'].mean())

df_test.isnull().sum()

INCIDENT_ID    0
DATE           0
X_1            0
X_2            0
X_3            0
X_4            0
X_5            0
X_6            0
X_7            0
X_8            0
X_9            0
X_10           0
X_11           0
X_12           0
X_13           0
X_14           0
X_15           0
dtype: int64

Now I checked my target distribution.
22788 samples are having value 1 as output, ie, server getting hacked.

Whereas only 1068 values are of 0 which accounts for only 4.477% of dataset.

This dataset is **highly biased**.

On observation from the competition page, I identified 50% test output is '0' & rest 50% is '1'

In [7]:
print(df_train.MULTIPLE_OFFENSE.value_counts())

value = df_train.MULTIPLE_OFFENSE.value_counts()[0]/ len(df_train) * 100
print("Samples having value 0: {:.3f} %".format(value))
value = df_train.MULTIPLE_OFFENSE.value_counts()[1]/ len(df_train) * 100
print("Samples having value 1: {:.3f} %".format(value))

1    22788
0     1068
Name: MULTIPLE_OFFENSE, dtype: int64
Samples having value 0: 4.477 %
Samples having value 1: 95.523 %

Get the correlation table, you can use 'pearson' or 'kendall' as well

In [8]:
df_train.corr(method ='spearman')

,X_1,X_2,X_3,X_4,X_5,X_6,X_7,X_8,X_9,X_10,X_11,X_12,X_13,X_14,X_15,MULTIPLE_OFFENSE
X_1,1.000000,0.067816,0.060875,0.082605,0.020635,0.687789,0.687938,-0.083854,-0.013102,-0.002661,-0.045533,-0.082069,0.096541,-0.002223,0.006922,-0.002555
X_2,0.067816,1.000000,0.995237,-0.091863,-0.294765,0.136519,0.065329,-0.041011,-0.039933,-0.017594,0.021130,-0.112514,0.012572,0.020228,0.074044,-0.031977
X_3,0.060875,0.995237,1.000000,-0.078422,-0.299386,0.136293,0.069739,-0.037209,-0.039658,-0.015479,0.022173,-0.109887,0.011825,0.018723,0.069418,-0.034230
X_4,0.082605,-0.091863,-0.078422,1.000000,0.458852,0.004957,0.127098,0.089489,0.023858,0.053417,-0.024443,0.083226,-0.028753,-0.027753,-0.087192,-0.002071
X_5,0.020635,-0.294765,-0.299386,0.458852,1.000000,-0.123322,0.002505,0.039228,0.061670,0.052847,-0.030012,0.108276,-0.041838,-0.005406,-0.076181,-0.004280
X_6,0.687789,0.136519,0.136293,0.004957,-0.123322,1.000000,0.566511,-0.092092,0.058280,0.007075,-0.027579,-0.116743,0.112632,-0.025484,0.002298,-0.000713
X_7,0.687938,0.065329,0.069739,0.127098,0.002505,0.566511,1.000000,-0.007477,0.000343,0.023744,-0.004120,-0.023067,0.039300,-0.008143,-0.028884,-0.002451
X_8,-0.083854,-0.041011,-0.037209,0.089489,0.039228,-0.092092,-0.007477,1.000000,0.277869,0.148560,0.211493,0.336848,-0.124032,-0.022035,-0.104663,-0.020009
X_9,-0.013102,-0.039933,-0.039658,0.023858,0.061670,0.058280,0.000343,0.277869,1.000000,0.061666,0.084654,0.146583,-0.012822,-0.294428,-0.042447,-0.000094
X_10,-0.002661,-0.017594,-0.015479,0.053417,0.052847,0.007075,0.023744,0.148560,0.061666,1.000000,-0.037849,0.540287,-0.015442,-0.015877,-0.021432,-0.450028
X_11,-0.045533,0.021130,0.022173,-0.024443,-0.030012,-0.027579,-0.004120,0.211493,0.084654,-0.037849,1.000000,0.222934,-0.022929,-0.015860,-0.088590,0.103477
X_12,-0.082069,-0.112514,-0.109887,0.083226,0.108276,-0.116743,-0.023067,0.336848,0.146583,0.540287,0.222934,1.000000,-0.003975,-0.061705,-0.187477,-0.138216
X_13,0.096541,0.012572,0.011825,-0.028753,-0.041838,0.112632,0.039300,-0.124032,-0.012822,-0.015442,-0.022929,-0.003975,1.000000,-0.049228,-0.041560,0.009215
X_14,-0.002223,0.020228,0.018723,-0.027753,-0.005406,-0.025484,-0.008143,-0.022035,-0.294428,-0.015877,-0.015860,-0.061705,-0.049228,1.000000,0.050863,-0.015757
X_15,0.006922,0.074044,0.069418,-0.087192,-0.076181,0.002298,-0.028884,-0.104663,-0.042447,-0.021432,-0.088590,-0.187477,-0.041560,0.050863,1.000000,-0.026964
MULTIPLE_OFFENSE,-0.002555,-0.031977,-0.034230,-0.002071,-0.004280,-0.000713,-0.002451,-0.020009,-0.000094,-0.450028,0.103477,-0.138216,0.009215,-0.015757,-0.026964,1.000000

Lets define our aarays

In [9]:
x_train = df_train.drop(['INCIDENT_ID', 'DATE', 'MULTIPLE_OFFENSE'], axis = 1).to_numpy()
print('X Trian shape:',x_train.shape)

x_test = df_test.drop(['INCIDENT_ID', 'DATE'], axis = 1).to_numpy()
print('X Test shape:',x_test.shape)

y_train = df_train.MULTIPLE_OFFENSE
print('Y Trian shape:',y_train.shape)

X Trian shape: (23856, 15)
X Test shape: (15903, 15)
Y Trian shape: (23856,)

# Normalization

In [340]:
from sklearn import preprocessing
scaler = preprocessing.StandardScaler().fit(x_train)


x_train_norm =scaler.transform(x_train)
x_test_norm = scaler.transform(x_test)

# Logistic Regression

With the help of Grid Search CV, we obtained a recall score of **55.147** when we had our parameters as C = 100, L2 norm, 'newton-cg' as solver. Without Grid Search we got **55.016** as recall score

In [121]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import RepeatedStratifiedKFold

In [234]:
# define models and parameters
model = LogisticRegression()
solvers = ['newton-cg', 'lbfgs', 'liblinear']
penalty = ['l2']
c_values = [100, 10, 1.0, 0.1, 0.01]

In [319]:
# define grid search
grid = dict(solver = solvers, penalty = penalty, C = c_values)
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state = 32)
grid_search = GridSearchCV(estimator = model, param_grid = grid, n_jobs = -1, cv = cv, scoring='recall', error_score=0)
grid_result = grid_search.fit(x_train_norm, y_train)

Use it only for logistic regression

In [323]:
model.fit(x_train_norm, y_train)
y_test = model.predict(x_test_norm)

C:\Users\Utkarsh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

In [320]:
# summarize results
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
means = grid_search.cv_results_['mean_test_score']
stds = grid_search.cv_results_['std_test_score']
params = grid_search.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))

Best: 1.000000 using {'C': 0.1, 'penalty': 'l2', 'solver': 'newton-cg'}
0.997645 (0.001004) with: {'C': 100, 'penalty': 'l2', 'solver': 'newton-cg'}
0.997411 (0.000990) with: {'C': 100, 'penalty': 'l2', 'solver': 'lbfgs'}
0.997645 (0.001004) with: {'C': 100, 'penalty': 'l2', 'solver': 'liblinear'}
0.999532 (0.000357) with: {'C': 10, 'penalty': 'l2', 'solver': 'newton-cg'}
0.999532 (0.000357) with: {'C': 10, 'penalty': 'l2', 'solver': 'lbfgs'}
0.999532 (0.000357) with: {'C': 10, 'penalty': 'l2', 'solver': 'liblinear'}
0.999985 (0.000079) with: {'C': 1.0, 'penalty': 'l2', 'solver': 'newton-cg'}
0.999985 (0.000079) with: {'C': 1.0, 'penalty': 'l2', 'solver': 'lbfgs'}
0.999956 (0.000132) with: {'C': 1.0, 'penalty': 'l2', 'solver': 'liblinear'}
1.000000 (0.000000) with: {'C': 0.1, 'penalty': 'l2', 'solver': 'newton-cg'}
1.000000 (0.000000) with: {'C': 0.1, 'penalty': 'l2', 'solver': 'lbfgs'}
1.000000 (0.000000) with: {'C': 0.1, 'penalty': 'l2', 'solver': 'liblinear'}
1.000000 (0.000000) with: {'C': 0.01, 'penalty': 'l2', 'solver': 'newton-cg'}
1.000000 (0.000000) with: {'C': 0.01, 'penalty': 'l2', 'solver': 'lbfgs'}
1.000000 (0.000000) with: {'C': 0.01, 'penalty': 'l2', 'solver': 'liblinear'}

In [321]:
y_test = grid_result.predict(x_test_norm)

In [324]:
values, counts = np.unique(y_test, return_counts=True)
print(values, counts)

[1] [15903]

# Random Forest Classifier

With the help of Grid Search CV, we obtained a recall score of 94.645 when we had our parameters as max_features = 'log2 & n_estimators = 1000. scoring is based on 'accuracy'

Without Grid Search we got 55.016 as recall score.

In [326]:
from sklearn.ensemble import RandomForestClassifier
# define models and parameters
model = RandomForestClassifier()
n_estimators = [10, 100, 1000]
max_features = ['sqrt', 'log2']

In [342]:
# define grid search
grid = dict(n_estimators=n_estimators, max_features=max_features)
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
grid_search = GridSearchCV(estimator=model, param_grid=grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_result = grid_search.fit(x_train_norm, y_train)

In [343]:
# summarize results
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))

Best: 0.992888 using {'max_features': 'log2', 'n_estimators': 1000}
0.992105 (0.002112) with: {'max_features': 'sqrt', 'n_estimators': 10}
0.992734 (0.001287) with: {'max_features': 'sqrt', 'n_estimators': 100}
0.992860 (0.001426) with: {'max_features': 'sqrt', 'n_estimators': 1000}
0.991365 (0.002448) with: {'max_features': 'log2', 'n_estimators': 10}
0.992832 (0.001760) with: {'max_features': 'log2', 'n_estimators': 100}
0.992888 (0.001502) with: {'max_features': 'log2', 'n_estimators': 1000}

In [344]:
y_test = grid_result.predict(x_test_norm)
values, counts = np.unique(y_test, return_counts=True)
print(values, counts)

[0 1] [  668 15235]

# XGBoost


We obtained a recall score of 99.01. scoring is based on 'accuracy'.
Used Randomized Search CV

In [19]:
import xgboost as xgb
from sklearn.model_selection import cross_validate   #Additional scklearn functions
from sklearn import metrics
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV   #Perforing grid search

from datetime import datetime
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import StratifiedKFold
from xgboost import XGBClassifier

import warnings
warnings.filterwarnings('ignore')

In [11]:
def timer(start_time=None):
    if not start_time:
        start_time = datetime.now()
        return start_time
    elif start_time:
        thour, temp_sec = divmod((datetime.now() - start_time).total_seconds(), 3600)
        tmin, tsec = divmod(temp_sec, 60)
        print('\n Time taken: %i hours %i minutes and %s seconds.' % (thour, tmin, round(tsec, 2)))

In [29]:
# A parameter grid for XGBoost
params = {
        'min_child_weight': [1, 5, 10],
        'gamma': [0.5, 1, 1.5, 2, 5],
        'subsample': [0.6, 0.8, 1.0],
        'colsample_bytree': [0.6, 0.8, 1.0],
        'max_depth': [3, 4, 5]
        }

In [30]:
xgb = XGBClassifier(learning_rate=0.02, n_estimators=600, objective='binary:logistic',
                    silent=True, nthread=1)
folds = 3
param_comb = 5

skf = StratifiedKFold(n_splits=folds, shuffle = True, random_state = 1001)

random_search = RandomizedSearchCV(xgb, param_distributions=params, n_iter=param_comb, 
                                   scoring='accuracy', n_jobs=4, cv=skf.split(x_train, y_train), verbose=3, 
                                   random_state=1001 )

In [31]:
# Here we go
start_time = timer(None) # timing starts from this point for "start_time" variable
random_search.fit(x_train, y_train)
timer(start_time) # timing ends here for "start_time" variable

Fitting 3 folds for each of 5 candidates, totalling 15 fits

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  15 out of  15 | elapsed:  1.4min finished

[17:20:21] WARNING: C:\Users\Administrator\workspace\xgboost-win64_release_1.1.0\src\learner.cc:480:
Parameters: { silent } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.



 Time taken: 0 hours 1 minutes and 37.48 seconds.

In [32]:
# summarize results
grid_result = random_search
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))

Best: 0.998826 using {'subsample': 0.8, 'min_child_weight': 1, 'max_depth': 4, 'gamma': 1, 'colsample_bytree': 1.0}
0.998030 (0.000527) with: {'subsample': 1.0, 'min_child_weight': 5, 'max_depth': 3, 'gamma': 5, 'colsample_bytree': 1.0}
0.998742 (0.000572) with: {'subsample': 0.6, 'min_child_weight': 1, 'max_depth': 5, 'gamma': 1.5, 'colsample_bytree': 0.8}
0.998323 (0.000463) with: {'subsample': 0.8, 'min_child_weight': 5, 'max_depth': 5, 'gamma': 1, 'colsample_bytree': 0.8}
0.998449 (0.000485) with: {'subsample': 1.0, 'min_child_weight': 5, 'max_depth': 5, 'gamma': 5, 'colsample_bytree': 0.6}
0.998826 (0.000584) with: {'subsample': 0.8, 'min_child_weight': 1, 'max_depth': 4, 'gamma': 1, 'colsample_bytree': 1.0}

In [33]:
y_test = random_search.predict(x_test)
values, counts = np.unique(y_test, return_counts=True)
print(values, counts)

[0 1] [  720 15183]

# XG Boost

We obtained a recall score of 99.22. scoring is based on 'accuracy'.
Learing rate = 0.1

I started working on tuning my hyperparameters to increase the recall score.

In [366]:
xgb1 = XGBClassifier(
                    learning_rate =0.1,
                    n_estimators=1000,
                    max_depth=5,
                    min_child_weight=1,
                    gamma=0,
                    subsample=0.8,
                    colsample_bytree=0.8,
                    objective= 'binary:logistic',
                    nthread=4,
                    scale_pos_weight=1,
                    seed=27)

In [367]:
xgb_param = xgb1.get_xgb_params()

xgtrain = xgb.DMatrix(x_train, label = y_train)

cvresult = xgb.cv(xgb_param, xgtrain, num_boost_round=xgb1.get_params()['n_estimators'], nfold=5,
    metrics='auc', early_stopping_rounds=50)

xgb1.set_params(n_estimators=cvresult.shape[0])

XGBClassifier(base_score=None, booster=None, colsample_bylevel=None,
              colsample_bynode=None, colsample_bytree=0.8, gamma=0, gpu_id=None,
              importance_type='gain', interaction_constraints=None,
              learning_rate=0.1, max_delta_step=None, max_depth=5,
              min_child_weight=1, missing=nan, monotone_constraints=None,
              n_estimators=112, n_jobs=None, nthread=4, num_parallel_tree=None,
              objective='binary:logistic', random_state=None, reg_alpha=None,
              reg_lambda=None, scale_pos_weight=1, seed=27, subsample=0.8,
              tree_method=None, validate_parameters=None, verbosity=None)

In [368]:
xgb1.fit(x_train, y_train,eval_metric='auc')

xgb1.score(x_train, y_train)

0.9997484909456741

In [363]:
y_test = xgb1.predict(x_test)
values, counts = np.unique(y_test, return_counts=True)
print(values, counts)

[0 1] [  723 15180]

# Tune max_depth and min_child_weight

In [36]:
param_test1 = {
 'max_depth':range(3,10,2),
 'min_child_weight':range(1,6,2)
}

gsearch1 = GridSearchCV(estimator = XGBClassifier( learning_rate =0.1, n_estimators=140, max_depth=5,
            min_child_weight=1, gamma=0, subsample=0.8, colsample_bytree=0.8,
            objective= 'binary:logistic', nthread=4, scale_pos_weight=1, seed=27), verbose = 10, 
            param_grid = param_test1, scoring='roc_auc',n_jobs=4,iid=False, cv=5)

In [37]:
gsearch1.fit(x_train, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 tasks      | elapsed:    3.4s
[Parallel(n_jobs=4)]: Done  10 tasks      | elapsed:    5.3s
[Parallel(n_jobs=4)]: Done  17 tasks      | elapsed:   10.9s
[Parallel(n_jobs=4)]: Done  24 tasks      | elapsed:   17.2s
[Parallel(n_jobs=4)]: Done  33 tasks      | elapsed:   30.1s
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:   40.8s
[Parallel(n_jobs=4)]: Done  53 tasks      | elapsed:   56.9s
[Parallel(n_jobs=4)]: Done  60 out of  60 | elapsed:  1.1min remaining:    0.0s
[Parallel(n_jobs=4)]: Done  60 out of  60 | elapsed:  1.1min finished

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=XGBClassifier(base_score=None, booster=None,
                                     colsample_bylevel=None,
                                     colsample_bynode=None,
                                     colsample_bytree=0.8, gamma=0, gpu_id=None,
                                     importance_type='gain',
                                     interaction_constraints=None,
                                     learning_rate=0.1, max_delta_step=None,
                                     max_depth=5, min_child_weight=1,
                                     missing=nan, monotone_constraints=None,
                                     n_...
                                     objective='binary:logistic',
                                     random_state=None, reg_alpha=None,
                                     reg_lambda=None, scale_pos_weight=1,
                                     seed=27, subsample=0.8, tree_method=None,
                                     validate_parameters=None, verbosity=None),
             iid=False, n_jobs=4,
             param_grid={'max_depth': range(3, 10, 2),
                         'min_child_weight': range(1, 6, 2)},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='roc_auc', verbose=10)

In [39]:
# summarize results
grid_result = gsearch1
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))

Best: 0.998826 using {'subsample': 0.8, 'min_child_weight': 1, 'max_depth': 4, 'gamma': 1, 'colsample_bytree': 1.0}
0.998030 (0.000527) with: {'subsample': 1.0, 'min_child_weight': 5, 'max_depth': 3, 'gamma': 5, 'colsample_bytree': 1.0}
0.998742 (0.000572) with: {'subsample': 0.6, 'min_child_weight': 1, 'max_depth': 5, 'gamma': 1.5, 'colsample_bytree': 0.8}
0.998323 (0.000463) with: {'subsample': 0.8, 'min_child_weight': 5, 'max_depth': 5, 'gamma': 1, 'colsample_bytree': 0.8}
0.998449 (0.000485) with: {'subsample': 1.0, 'min_child_weight': 5, 'max_depth': 5, 'gamma': 5, 'colsample_bytree': 0.6}
0.998826 (0.000584) with: {'subsample': 0.8, 'min_child_weight': 1, 'max_depth': 4, 'gamma': 1, 'colsample_bytree': 1.0}

In [42]:
print(gsearch1.score(x_train, y_train))

y_test = gsearch1.predict(x_test)
values, counts = np.unique(y_test, return_counts=True)
print(values, counts)

0.9995808182427901
[0 1] [  720 15183]

In [45]:
param_test2 = {
 'max_depth':[4,5,6],
 'min_child_weight':[1,2,3]
}
gsearch2 = GridSearchCV(estimator = XGBClassifier( learning_rate=0.1, n_estimators=140, max_depth=5,
    min_child_weight=1, gamma=0, subsample=0.8, colsample_bytree=0.8,
    objective= 'binary:logistic', nthread=4, scale_pos_weight=1,seed=27), verbose = 10,
    param_grid = param_test2, scoring='roc_auc',n_jobs=4,iid=False, cv=5)

gsearch2.fit(x_train, y_train)
gsearch2.grid_scores_, gsearch2.best_params_, gsearch2.best_score_

Fitting 5 folds for each of 9 candidates, totalling 45 fits

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 tasks      | elapsed:    7.6s
[Parallel(n_jobs=4)]: Done  10 tasks      | elapsed:   10.2s
[Parallel(n_jobs=4)]: Done  17 tasks      | elapsed:   18.8s
[Parallel(n_jobs=4)]: Done  24 tasks      | elapsed:   25.3s
[Parallel(n_jobs=4)]: Done  33 tasks      | elapsed:   40.4s
[Parallel(n_jobs=4)]: Done  43 out of  45 | elapsed:   52.1s remaining:    2.3s
[Parallel(n_jobs=4)]: Done  45 out of  45 | elapsed:   53.9s finished

AttributeError: 'GridSearchCV' object has no attribute 'grid_scores_'

# Tune gamma

At the end my new gamma was 0.2

In [50]:
param_test3 = {
 'gamma':[i/10.0 for i in range(0,5)]
}

gsearch3 = GridSearchCV(estimator = XGBClassifier( learning_rate =0.1, n_estimators=140, max_depth = 5,
    min_child_weight = 1, gamma=0, subsample=0.8, colsample_bytree=0.8,
    objective= 'binary:logistic', nthread=4, scale_pos_weight=1,seed=27), verbose = 10,
    param_grid = param_test3, scoring='roc_auc',n_jobs=4,iid=False, cv=5)

gsearch3.fit(x_train, y_train)
gsearch3.cv_results_, gsearch3.best_params_, gsearch3.best_score_

Fitting 5 folds for each of 5 candidates, totalling 25 fits

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 tasks      | elapsed:    4.7s
[Parallel(n_jobs=4)]: Done  10 tasks      | elapsed:    9.7s
[Parallel(n_jobs=4)]: Done  17 tasks      | elapsed:   20.4s
[Parallel(n_jobs=4)]: Done  21 out of  25 | elapsed:   26.1s remaining:    4.9s
[Parallel(n_jobs=4)]: Done  25 out of  25 | elapsed:   28.3s finished

({'mean_fit_time': array([2.21494207, 3.58047929, 5.51717877, 5.04533291, 4.93908896]),
  'std_fit_time': array([0.22368023, 1.11109142, 0.4558567 , 0.38645037, 1.37287706]),
  'mean_score_time': array([0.01615677, 0.0269021 , 0.03367624, 0.04009023, 0.02899094]),
  'std_score_time': array([0.00074652, 0.00799101, 0.01080197, 0.00415256, 0.00570641]),
  'param_gamma': masked_array(data=[0.0, 0.1, 0.2, 0.3, 0.4],
               mask=[False, False, False, False, False],
         fill_value='?',
              dtype=object),
  'params': [{'gamma': 0.0},
   {'gamma': 0.1},
   {'gamma': 0.2},
   {'gamma': 0.3},
   {'gamma': 0.4}],
  'split0_test_score': array([0.99940025, 0.99933567, 0.99943921, 0.9993859 , 0.99940948]),
  'split1_test_score': array([0.99999282, 0.99998872, 0.99999077, 0.99999282, 0.9999918 ]),
  'split2_test_score': array([0.9999877 , 0.99999487, 0.99998872, 0.99998872, 0.99999077]),
  'split3_test_score': array([0.99997836, 0.9999763 , 0.99997836, 0.99997836, 0.99997733]),
  'split4_test_score': array([0.99999279, 0.99999176, 0.99999279, 0.99999176, 0.99999176]),
  'mean_test_score': array([0.99987039, 0.99985746, 0.99987797, 0.99986751, 0.99987223]),
  'std_test_score': array([0.00023513, 0.00026098, 0.00021944, 0.00024086, 0.00023144]),
  'rank_test_score': array([3, 5, 1, 4, 2])},
 {'gamma': 0.2},
 0.9998779720510637)

# Tune subsample and colsample_bytree

At the end my subsample value was 0.6 & colsample_bytree value was 0.6
I also tried to reduce my learning rate but the recall score didn't improved further.

In [53]:
param_test4 = {
 'subsample':[i/10.0 for i in range(6,10)],
 'colsample_bytree':[i/10.0 for i in range(6,10)]
}
gsearch4 = GridSearchCV(estimator = XGBClassifier( learning_rate = 0.1, n_estimators=177, max_depth=5,
 min_child_weight=1, gamma=0.0, subsample=0.8, colsample_bytree=0.8,
 objective= 'binary:logistic', nthread=4, scale_pos_weight=1,seed=27), verbose = 10,
 param_grid = param_test4, scoring='roc_auc',n_jobs=4,iid=False, cv=5)

gsearch4.fit(x_train, y_train)
gsearch4.cv_results_, gsearch4.best_params_, gsearch4.best_score_

Fitting 5 folds for each of 16 candidates, totalling 80 fits

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 tasks      | elapsed:    7.7s
[Parallel(n_jobs=4)]: Done  10 tasks      | elapsed:   12.0s
[Parallel(n_jobs=4)]: Done  17 tasks      | elapsed:   21.8s
[Parallel(n_jobs=4)]: Done  24 tasks      | elapsed:   28.6s
[Parallel(n_jobs=4)]: Done  33 tasks      | elapsed:   43.7s
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:   54.9s
[Parallel(n_jobs=4)]: Done  53 tasks      | elapsed:  1.2min
[Parallel(n_jobs=4)]: Done  64 tasks      | elapsed:  1.4min
[Parallel(n_jobs=4)]: Done  80 out of  80 | elapsed:  1.8min finished

({'mean_fit_time': array([2.31657395, 3.2175951 , 4.9187469 , 4.86720896, 5.69926047,
         4.92037978, 5.31860213, 4.85597296, 6.15350728, 5.70588078,
         5.58397903, 5.71282105, 6.13826871, 6.4730937 , 6.10452194,
         5.61596308]),
  'std_fit_time': array([0.13888994, 0.72769894, 0.5801794 , 0.27248886, 0.30526382,
         0.03892177, 0.35920189, 0.32126025, 0.41836194, 0.57358467,
         0.52473454, 0.3035964 , 0.66935739, 0.64721877, 0.29388107,
         0.30205526]),
  'mean_score_time': array([0.02499371, 0.03321791, 0.04001789, 0.04248242, 0.041471  ,
         0.03728509, 0.03880739, 0.0350976 , 0.03428655, 0.04125571,
         0.03484087, 0.04061537, 0.0369133 , 0.034902  , 0.0414279 ,
         0.03300757]),
  'std_score_time': array([0.00765331, 0.02452109, 0.01299243, 0.00555236, 0.00702404,
         0.00782908, 0.00700363, 0.00771201, 0.00683056, 0.0083428 ,
         0.00495061, 0.00765409, 0.0097129 , 0.00530583, 0.00463444,
         0.00507743]),
  'param_colsample_bytree': masked_array(data=[0.6, 0.6, 0.6, 0.6, 0.7, 0.7, 0.7, 0.7, 0.8, 0.8, 0.8,
                     0.8, 0.9, 0.9, 0.9, 0.9],
               mask=[False, False, False, False, False, False, False, False,
                     False, False, False, False, False, False, False, False],
         fill_value='?',
              dtype=object),
  'param_subsample': masked_array(data=[0.6, 0.7, 0.8, 0.9, 0.6, 0.7, 0.8, 0.9, 0.6, 0.7, 0.8,
                     0.9, 0.6, 0.7, 0.8, 0.9],
               mask=[False, False, False, False, False, False, False, False,
                     False, False, False, False, False, False, False, False],
         fill_value='?',
              dtype=object),
  'params': [{'colsample_bytree': 0.6, 'subsample': 0.6},
   {'colsample_bytree': 0.6, 'subsample': 0.7},
   {'colsample_bytree': 0.6, 'subsample': 0.8},
   {'colsample_bytree': 0.6, 'subsample': 0.9},
   {'colsample_bytree': 0.7, 'subsample': 0.6},
   {'colsample_bytree': 0.7, 'subsample': 0.7},
   {'colsample_bytree': 0.7, 'subsample': 0.8},
   {'colsample_bytree': 0.7, 'subsample': 0.9},
   {'colsample_bytree': 0.8, 'subsample': 0.6},
   {'colsample_bytree': 0.8, 'subsample': 0.7},
   {'colsample_bytree': 0.8, 'subsample': 0.8},
   {'colsample_bytree': 0.8, 'subsample': 0.9},
   {'colsample_bytree': 0.9, 'subsample': 0.6},
   {'colsample_bytree': 0.9, 'subsample': 0.7},
   {'colsample_bytree': 0.9, 'subsample': 0.8},
   {'colsample_bytree': 0.9, 'subsample': 0.9}],
  'split0_test_score': array([0.99944331, 0.99964118, 0.99965143, 0.99963195, 0.99949662,
         0.99945049, 0.99950995, 0.99956736, 0.99914908, 0.9993777 ,
         0.99936847, 0.9995079 , 0.99928902, 0.99926134, 0.9993982 ,
         0.99956993]),
  'split1_test_score': array([0.99998872, 0.9999877 , 0.9999877 , 0.99999385, 0.99998872,
         0.99998975, 0.99999282, 0.9999918 , 0.9999877 , 0.99999282,
         0.99998975, 0.99999487, 0.9999877 , 0.99999385, 0.9999918 ,
         0.9999918 ]),
  'split2_test_score': array([0.99998975, 0.99999385, 0.99999487, 0.9999959 , 0.99998565,
         0.99998975, 0.9999918 , 0.9999959 , 0.99998155, 0.99998257,
         0.9999918 , 0.99999795, 0.99997642, 0.99998872, 0.99998565,
         0.9999959 ]),
  'split3_test_score': array([0.99997733, 0.99998455, 0.99998867, 0.99998661, 0.99998249,
         0.99998249, 0.99998558, 0.9999897 , 0.99998558, 0.99998455,
         0.99998455, 0.99998661, 0.99998558, 0.99998455, 0.99998249,
         0.99998661]),
  'split4_test_score': array([0.99998764, 0.99999588, 0.99999897, 1.        , 0.99999073,
         0.99999382, 0.99999382, 0.99999691, 0.99999073, 0.99999382,
         0.99999485, 0.99999691, 0.9999897 , 0.99999279, 0.99999382,
         0.99999382]),
  'mean_test_score': array([0.99987735, 0.99992063, 0.99992433, 0.99992166, 0.99988884,
         0.99988126, 0.99989479, 0.99990833, 0.99981893, 0.99986629,
         0.99986588, 0.99989685, 0.99984568, 0.99984425, 0.99987039,
         0.99990761]),
  'std_test_score': array([0.00021707, 0.00013979, 0.00013651, 0.00014492, 0.00019613,
         0.00021542, 0.00019244, 0.00017051, 0.00033494, 0.00024434,
         0.00024873, 0.00019451, 0.00027837, 0.00029147, 0.00023613,
         0.00016887]),
  'rank_test_score': array([10,  3,  1,  2,  8,  9,  7,  4, 16, 12, 13,  6, 14, 15, 11,  5])},
 {'colsample_bytree': 0.6, 'subsample': 0.8},
 0.9999243275695392)

# Getting csv file

At the end recall score achieved: 99.44

In [54]:
y_test = gsearch4.predict(x_test)
values, counts = np.unique(y_test, return_counts=True)
print(values, counts)

[0 1] [  722 15181]

In [55]:
df_submit = pd.DataFrame(df_test['INCIDENT_ID'], columns= submit.columns)
df_submit['MULTIPLE_OFFENSE'] = y_test.tolist()
df_submit.to_csv('output.csv', index=False)

df_submit.head()

  INCIDENT_ID  MULTIPLE_OFFENSE
0   CR_195453                 1
1   CR_103520                 1
2   CR_196089                 1
3   CR_112195                 1
4   CR_149832                 1